version: '3.8'
services:
  dataCollection:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: joshproject
      POSTGRES_PASSWORD: 787897
      POSTGRES_DB: datacollection
    networks:
      - datacollection
networks:
  datacollection: 